service: charcookery

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

