name: Deploy master branch

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Package dependencies to .zip
      run: zip aws_lambda_artifact.zip -r node_modules

    - name: Build
      run: npm run build

    - name: Copy openapi.yml to build folder
      run: cp ./src/docs/openapi.yml dist

    - name: Package build to .zip
      run: zip aws_lambda_artifact.zip -r dist

    - name: Package other files to .zip
      run: |
        zip aws_lambda_artifact.zip package.json
        zip aws_lambda_artifact.zip package-lock.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
        --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
        --zip-file fileb://aws_lambda_artifact.zip

    - name: Cleanup
      run: rm -rf aws_lambda_artifact.zip
